### ISSUE TITLE
Use in NodeJS?

### ISSUE THREAD

**Issue by DylanPiercey** [asvd/microlight#2]
This might be out of scope since your goal was to create something super tiny (great job by the way!), however it would be sweet if this could work server side, IE: given a string of html, output a string of html.

Feel free to close this if it is out of scope.

**Comment by asvd** [comment]
It's definitely out of scope, but the question itself is pretty interesting.

I suspect there might be not that much sence of highlighting the code on server side. There is a related discussion: https://news.ycombinator.com/item?id=11803389
