### ISSUE TITLE
Use options instead hardcoded variables to customize style

### ISSUE THREAD

**Issue by midudev** [asvd/microlight#4]
Hi! Awesome library, congrats! :)

I would like to ask for a way to accept a options object in order to customize a bit the style. For example, instead text-shadow, it might accept other kind of style or a tweaked one. I think some kind of customization would be great without compromising the size of the file.

Thanks!

**Comment by boneskull** [comment]
Along these lines, there's a _significant_ amount of jank when scrolling this project's page on an iPhone 6 (iOS 9.3.2). My guess is the text shadow.
